name: Run tests

on:
  push:

env:
  pytest_cpus: 2

jobs:
  test:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
    
      - name: Setup pytest arguments
        run: |
          echo "Will be using $pytest_cpus cpu cores to run tests"
          export xdist_args="-n $pytest_cpus" >> $GITHUB_ENV

      - name: Run tests
        run: echo $xdist_args