name: Run tests

on:
    push:

env:
    PYTHON_VERSIONS: '["3.10", "3.11", "3.12"]'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Test
              run: echo "$PYTHON_VERSIONS"