name: Run tests

on:
  gollum

env:
  pytest_cpus: 2 # How many cpu cores will be used to run tests
  pytest_cov_dir: 'dgmr' # pytest-cov will look at the coverage for this directory

jobs:
  test:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run tests
        run: |
          echo pytest -n $pytest_cpus --cov-report=xml --cov=$pytest_cov_dir
      
      - name: Report coverage
        run: |
          coverage report -m
      
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: false