name: Run tests

on:
  push:

env:
  PYTHON_VERSIONS: '["3.10", "3.11", "3.12"]'
  OS_LIST: '["ubuntu-latest", "macos-latest"]'

jobs:
  run-python-tests:
    strategy:
      matrix:
        python-version: $PYTHON_VERSIONS
        os: $OS_LIST

    runs-on: ${{ matrix.os }}


    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
          pip install -r tests/requirements.txt

      - name: Run tests
        run: pytest tests