name: Run tests

on:
  push:

env:
  pytest_cpus: 2 # How many cpu cores will be used to run tests
  pytest_cov_dir: 'dgmr' # pytest-cov will look at the coverage for this directory

jobs:
  run-python-tests:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"] # The python versions to run tests on
        os: ["ubuntu-latest", "macos-latest"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r tests/requirements.txt

      - name: Run tests
        run: |
          pytest -n $pytest_cpus --cov-report=xml --cov=$pytest_cov_dir
      
      - name: Report coverage
        run: |
          coverage report -m
      
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: false
